services:
  backend:
    image: alexandria-backend:latest
    container_name: backend
    volumes:
      - ./data:/code/data  # For our database
      - ./images:/images # For our image assets
    env_file:
      - ./backend/.env.docker
    ports:
      - "8000:8000"
  
  frontend:
    image: alexandria-frontend:latest
    container_name: frontend
    env_file:
      - ./frontend/.env.development
    ports:
      - "3000:3000"