"""Ensure uniqueness of book_id field for Images

Revision ID: 411363141e85
Revises: dece0a6de018
Create Date: 2024-11-13 11:15:29.136982

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '411363141e85'
down_revision: Union[str, None] = 'dece0a6de018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_book_image', ['book_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_constraint('uq_book_image', type_='unique')
    # ### end Alembic commands ###
