"""removing cover_uri. made file storage/path too tightly coupled to database. will assemble image paths from unique IDs based on environment

Revision ID: 80e2a9ba5921
Revises: 14f6b5b9dd3a
Create Date: 2024-09-19 10:08:15.502774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80e2a9ba5921'
down_revision: Union[str, None] = '14f6b5b9dd3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'cover_uri')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('cover_uri', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
