"""Add sort_key and sort_direction to Bookshelf

Revision ID: 92d98cc30f7d
Revises: 
Create Date: 2024-08-28 22:40:03.008831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d98cc30f7d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookshelf', sa.Column('sort_key', sa.Enum('id', 'title', 'author', 'year', 'rating', name='sortkey'), nullable=False, server_default='id'))
    op.add_column('bookshelf', sa.Column('sort_direction', sa.Enum('ascending', 'descending', name='sortdirection'), nullable=False, server_default='ascending'))
    
    # Note:
    # I manually added the server_default above because existing bookshelf records couldn't have a NULL value
    # I then attempted to add additional commands to remove the default values that are included above for sort_key and sort_direction
    # It turns out that SQLite has no clean command for this, and the closest I could find involved renaming columns, creating new
    # columns, copying columns to each other, etc.
    # I ended up simply using DB Browser to manually modify the table definitions to remove the defaults
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookshelf', 'sort_direction')
    op.drop_column('bookshelf', 'sort_key')
    # ### end Alembic commands ###
