"""Removing OLID from book. Replaced with Book->Image relationship

Revision ID: dece0a6de018
Revises: c942f1eed4dd
Create Date: 2024-11-03 23:50:19.349488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dece0a6de018'
down_revision: Union[str, None] = 'c942f1eed4dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'olid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('olid', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
